#!/usr/bin/env python3
"""Compare DECtalk WAV baselines with current generated WAV files.

Purpose: verify golden DECtalk WAV outputs and optionally emit audio metrics.
Scope: deterministic RIFF/WAVE PCM files generated by the Linux baseline tools.
Behavior preservation: exact SHA-256 equality remains the success condition.
Limitations: metric reports describe byte/sample differences; they do not
approve speech-output changes.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import math
import struct
import sys
import wave
from pathlib import Path


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def read_wav(path: Path) -> tuple[wave._wave_params, list[int], bytes]:
    with wave.open(str(path), "rb") as handle:
        params = handle.getparams()
        data = handle.readframes(params.nframes)

    if params.nchannels != 1:
        raise ValueError(f"{path}: expected mono WAV, got {params.nchannels} channels")
    if params.sampwidth != 2:
        raise ValueError(f"{path}: expected 16-bit samples, got {params.sampwidth * 8}-bit")

    count = len(data) // 2
    samples = list(struct.unpack(f"<{count}h", data))
    return params, samples, data


def rms(samples: list[int]) -> float:
    if not samples:
        return 0.0
    return math.sqrt(sum(sample * sample for sample in samples) / len(samples))


def peak(samples: list[int]) -> int:
    if not samples:
        return 0
    return max(map(abs, samples))


def compare_pair(expected: Path, actual: Path) -> tuple[list[str], dict[str, object]]:
    problems: list[str] = []
    expected_params, expected_samples, expected_data = read_wav(expected)
    actual_params, actual_samples, actual_data = read_wav(actual)
    expected_hash = sha256(expected)
    actual_hash = sha256(actual)
    paired_count = min(len(expected_samples), len(actual_samples))
    max_abs_delta = 0
    if paired_count:
        max_abs_delta = max(
            abs(expected_samples[index] - actual_samples[index])
            for index in range(paired_count)
        )

    metrics: dict[str, object] = {
        "file": expected.name,
        "status": "OK",
        "expected_sha256": expected_hash,
        "actual_sha256": actual_hash,
        "expected_frames": expected_params.nframes,
        "actual_frames": actual_params.nframes,
        "expected_sample_rate": expected_params.framerate,
        "actual_sample_rate": actual_params.framerate,
        "expected_peak": peak(expected_samples),
        "actual_peak": peak(actual_samples),
        "expected_rms": f"{rms(expected_samples):.2f}",
        "actual_rms": f"{rms(actual_samples):.2f}",
        "max_abs_delta": max_abs_delta,
    }

    if expected_params != actual_params:
        problems.append(f"params differ: expected {expected_params}, actual {actual_params}")

    if expected_hash == actual_hash:
        return problems, metrics

    problems.append(f"sha256 differs: expected {expected_hash}, actual {actual_hash}")

    if len(expected_samples) != len(actual_samples):
        problems.append(
            f"sample count differs: expected {len(expected_samples)}, actual {len(actual_samples)}"
        )

    if paired_count:
        problems.append(f"max abs sample delta: {max_abs_delta}")
        problems.append(f"expected peak/rms: {peak(expected_samples)}/{rms(expected_samples):.2f}")
        problems.append(f"actual peak/rms: {peak(actual_samples)}/{rms(actual_samples):.2f}")
    elif expected_data != actual_data:
        problems.append("audio payload differs and no samples were available to compare")

    metrics["status"] = "DIFFER"
    return problems, metrics


def write_metrics(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "file",
        "status",
        "expected_sha256",
        "actual_sha256",
        "expected_frames",
        "actual_frames",
        "expected_sample_rate",
        "actual_sample_rate",
        "expected_peak",
        "actual_peak",
        "expected_rms",
        "actual_rms",
        "max_abs_delta",
    ]
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, delimiter="\t")
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--expected",
        type=Path,
        default=Path("tests/golden/audio/us"),
        help="directory containing baseline WAV files",
    )
    parser.add_argument(
        "--actual",
        type=Path,
        required=True,
        help="directory containing newly generated WAV files",
    )
    parser.add_argument(
        "--metrics-out",
        type=Path,
        help="optional TSV file for per-WAV hash, frame, peak, RMS, and delta metrics",
    )
    args = parser.parse_args()

    expected_files = sorted(args.expected.glob("*.wav"))
    if not expected_files:
        print(f"error: no WAV files found in {args.expected}", file=sys.stderr)
        return 2

    failed = False
    metric_rows: list[dict[str, object]] = []
    for expected in expected_files:
        actual = args.actual / expected.name
        if not actual.exists():
            print(f"{expected.name}: missing actual file {actual}")
            metric_rows.append(
                {
                    "file": expected.name,
                    "status": "MISSING",
                    "expected_sha256": sha256(expected),
                    "actual_sha256": "",
                    "expected_frames": "",
                    "actual_frames": "",
                    "expected_sample_rate": "",
                    "actual_sample_rate": "",
                    "expected_peak": "",
                    "actual_peak": "",
                    "expected_rms": "",
                    "actual_rms": "",
                    "max_abs_delta": "",
                }
            )
            failed = True
            continue
        problems, metrics = compare_pair(expected, actual)
        metric_rows.append(metrics)
        if problems:
            failed = True
            print(f"{expected.name}: DIFFER")
            for problem in problems:
                print(f"  {problem}")
        else:
            print(f"{expected.name}: OK")

    if args.metrics_out is not None:
        write_metrics(args.metrics_out, metric_rows)

    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
